language: php

sudo: false

php:
  - 7.4
#  - 7.3
#  - 7.2

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Codesniffer.
  - composer global require squizlabs/php_codesniffer:3.5.5

  # Coder.
  - composer global require drupal/coder:8.3.9

install:
  - cd ../
  - git clone --branch 8.9.x https://git.drupalcode.org/project/drupal.git
  - mv gatsby_orchestrator drupal/modules/gatsby_orchestrator
  - cd drupal && composer install

script:
  - ls -al
  - pwd

  # Run code sniffer.
  - phpcs --report=full --standard=/home/travis/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal/ modules/gatsby_orchestrator
#
#  # Drupal "SimpleTests" via run-tests.sh
#  - cd $TRAVIS_BUILD_DIR/drupal
#  - php core/scripts/run-tests.sh --verbose --color --module $MODULE_NAME --php $(which php) --url http://127.0.0.1:8080
#
#  # PHP Unit Tests
#  - cd $TRAVIS_BUILD_DIR/drupal
#  - phpunit -c core/phpunit.xml.dist modules/$MODULE_NAME --debug --testdox
#
#
#  # Behat Tests - RUN THESE LAST OTHERWISE PHPUNIT WILL FAIL BECAUSE OF DEPENDENCY CONFLICTS
#  - cd $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME
#  - composer install
#  - vendor/bin/behat --config tests/behat/behat.yml
